import type { CaseStudy } from "./types";

export const CASE_STUDIES: CaseStudy[] = [
  {
    slug: "mor-matcha",
    projectName: "Mor Matcha",
    category: "E-commerce Website Development",
    description: "A focused storefront for clean matcha energy, with product education and a direct path to the Mor'nin Blend.",
    contentFile: "content/case-studies/mor-matcha.md",
    caseStudyTitle: "Stopping the Slow Bleed at Checkout",
    coverImage: "/portfolio/mor-matcha.png",
    projectLink: "https://www.mormatcha.com/",
    metrics: [{ label: "Brand Focus", value: "Matcha Ritual" }],
    featured: true,
  },
  {
    slug: "linen-way",
    projectName: "Linen Way",
    category: "E-commerce Website Development",
    description: "A warm, editorial shopping experience for sustainable linen, wool, and alpaca textures.",
    contentFile: "content/case-studies/linen-way.md",
    caseStudyTitle: "Surviving the Biggest Day of the Year",
    coverImage: "/portfolio/linen-way.png",
    projectLink: "https://linenway.com/",
    metrics: [{ label: "Founded", value: "2002" }],
    featured: true,
  },
  {
    slug: "matilda-jewellery",
    projectName: "Matilda Jewellery",
    category: "Creative & Brand CRO",
    description: "A refined jewellery storefront rooted in Portuguese craft, small details, and intentional design.",
    contentFile: "content/case-studies/matilda-jewellery.md",
    coverImage: "/portfolio/matilda-jewellery.png",
    projectLink: "https://www.matildajewellery.com/",
    metrics: [{ label: "Made In", value: "Portugal" }],
    featured: true,
  },
  {
    slug: "babo-botanicals",
    projectName: "Babo Botanicals",
    category: "E-commerce Website Development",
    description: "A bright, approachable skincare experience that makes mineral SPF and botanical care easy to choose.",
    contentFile: "content/case-studies/babo-botanicals.md",
    coverImage: "/portfolio/babo-botanicals.png",
    projectLink: "https://www.babobotanicals.com/",
    metrics: [{ label: "Brand Roots", value: "15 Years" }],
    featured: true,
  },
  {
    slug: "luxeaura",
    projectName: "LuxeAura Fashion",
    category: "E-commerce Store Development",
    description: "[EXAMPLE] Engineered a high-speed Shopify Plus experience with bespoke one-click checkout, dynamic bundle builder, and mobile CRO that increased store revenue by 310%.",
    coverImage: "/case-studies/luxeaura/cover.png",
    mobileImage: "/case-studies/luxeaura/mobile.png",
    designTools: "Figma, Adobe Photoshop",
    backend: "Shopify Plus Admin",
    programmingLanguage: "Liquid, Tailwind CSS, TypeScript",
    projectLink: "https://example.com/luxeaura",
    metrics: [{ label: "Revenue Growth", value: "+310%" }, { label: "Conversion Rate", value: "4.8%" }, { label: "Mobile Speed Score", value: "99/100" }, { label: "Average Order Value", value: "₹3,450" }],
    gallery: ["/case-studies/luxeaura/gallery-1.png", "/case-studies/luxeaura/gallery-2.png"],
    featured: true,
  },
  {
    slug: "glowbotanics",
    projectName: "GlowBotanics Skincare",
    category: "Performance Marketing",
    description: "[EXAMPLE] Deployed high-converting UGC creative pipelines and multi-channel Meta & Google shopping funnels that generated $4.2M in revenue at a 4.6x blended ROAS.",
    coverImage: "/case-studies/glowbotanics/cover.png",
    mobileImage: "/case-studies/glowbotanics/mobile.png",
    designTools: "CapCut, Adobe Premiere Pro, Figma",
    backend: "Meta Ads Manager, Google Ads",
    projectLink: "https://example.com/glowbotanics",
    metrics: [{ label: "Ad Spend", value: "₹65,40,000" }, { label: "Generated Revenue", value: "₹3,02,00,000" }, { label: "Blended ROAS", value: "4.62x" }, { label: "CAC Reduction", value: "-42%" }],
    gallery: ["/case-studies/glowbotanics/gallery-1.png", "/case-studies/glowbotanics/gallery-2.png"],
  },
  {
    slug: "aura-jewelry",
    projectName: "Aura Jewelry DTC",
    category: "E-commerce Store Development",
    description: "[EXAMPLE] Crafted founder-led video storytelling, interactive 3D product visualizers, and seamless cart upsells that lifted average order value by $68.",
    coverImage: "/case-studies/aura-jewelry/cover.png",
    mobileImage: "/case-studies/aura-jewelry/mobile.png",
    designTools: "Figma, Blender 3D",
    backend: "Shopify Admin",
    programmingLanguage: "Liquid, React, Three.js",
    projectLink: "https://example.com/aura-jewelry",
    metrics: [{ label: "AOV Lift", value: "+48%" }, { label: "Checkout CVR", value: "5.2%" }, { label: "Return Customer Rate", value: "34%" }],
    gallery: ["/case-studies/aura-jewelry/gallery-1.png"],
  },
  {
    slug: "vitalis-wellness",
    projectName: "Vitalis Wellness DTC",
    category: "Subscriptions & Retention",
    description: "[EXAMPLE] Integrated automated Recharge subscription flows, seamless customer portals, and SMS lifecycle campaigns delivering consistent compounding revenue with 18k+ subscribers.",
    coverImage: "/case-studies/vitalis-wellness/cover.png",
    mobileImage: "/case-studies/vitalis-wellness/mobile.png",
    designTools: "Figma",
    backend: "Recharge, Klaviyo, Shopify",
    programmingLanguage: "Liquid, JavaScript",
    projectLink: "https://example.com/vitalis-wellness",
    metrics: [{ label: "Monthly Subscribers", value: "18,400+" }, { label: "Retention Rate (90-Day)", value: "68%" }, { label: "MRR Growth", value: "+185%" }],
  },
];

export const caseStudies = CASE_STUDIES;
