import type { CaseStudy } from "./types";

export const CASE_STUDIES: CaseStudy[] = [
  {
    slug: "mor-matcha",
    projectName: "Mor Matcha",
    category: "E-commerce Website Development",
    description: "A focused storefront for clean matcha energy, with product education and a direct path to the Mor'nin Blend.",
    contentFile: "content/case-studies/mor-matcha.md",
    caseStudyTitle: "Stopping the Slow Bleed at Checkout",
    coverImage: "/portfolio/mor-matcha.png",
    projectLink: "https://www.mormatcha.com/",
    metrics: [{ label: "Brand Focus", value: "Matcha Ritual" }],
    featured: true,
  },
  {
    slug: "linen-way",
    projectName: "Linen Way",
    category: "E-commerce Website Development",
    description: "A warm, editorial shopping experience for sustainable linen, wool, and alpaca textures.",
    contentFile: "content/case-studies/linen-way.md",
    caseStudyTitle: "Surviving the Biggest Day of the Year",
    coverImage: "/portfolio/linen-way.png",
    projectLink: "https://linenway.com/",
    metrics: [{ label: "Founded", value: "2002" }],
    featured: true,
  },
  {
    slug: "matilda-jewellery",
    projectName: "Matilda Jewellery",
    category: "Creative & Brand CRO",
    description: "A refined jewellery storefront rooted in Portuguese craft, small details, and intentional design.",
    contentFile: "content/case-studies/matilda-jewellery.md",
    coverImage: "/portfolio/matilda-jewellery.png",
    projectLink: "https://www.matildajewellery.com/",
    metrics: [{ label: "Made In", value: "Portugal" }],
    featured: true,
  },
  {
    slug: "babo-botanicals",
    projectName: "Babo Botanicals",
    category: "E-commerce Website Development",
    description: "A bright, approachable skincare experience that makes mineral SPF and botanical care easy to choose.",
    contentFile: "content/case-studies/babo-botanicals.md",
    coverImage: "/portfolio/babo-botanicals.png",
    projectLink: "https://www.babobotanicals.com/",
    metrics: [{ label: "Brand Roots", value: "15 Years" }],
    featured: true,
  },
  {
    slug: "mana-yerba-mate",
    projectName: "Mana Yerba Mate",
    category: "E-commerce Scaling & Operations",
    description: "A fast-growing energy drink brand that needed its backend operations to catch up with explosive order growth.",
    contentFile: "content/case-studies/mana-yerba-mate.md",
    coverImage: "/portfolio/mana-yerba-mate.png",
    projectLink: "https://en.manayerbamate.com/",
    metrics: [{ label: "Focus", value: "Operations & Fulfillment" }],
    featured: false,
},
  {
    slug: "experiment-beauty",
    projectName: "Experiment Beauty",
    category: "E-commerce Website Development",
    description: "A beauty brand with a genuinely stronger product that needed a store fast and polished enough to actually compete.",
    contentFile: "content/case-studies/experiment-beauty.md",
    coverImage: "/portfolio/experiment-beauty.png",
    projectLink: "https://experimentbeauty.com/",
    metrics: [{ label: "Focus", value: "Site Speed & Checkout UX" }],
    featured: false,
},
  {
    slug: "taneva",
    projectName: "Taneva",
    category: "E-commerce Website Development",
    description: "A spray tanning tent brand that needed its store to answer the questions buyers had before they'd feel ready to purchase.",
    contentFile: "content/case-studies/taneva.md",
    coverImage: "/portfolio/taneva.png",
    projectLink: "https://www.taneva.co.uk/",
    metrics: [{ label: "Focus", value: "Product Page UX & Pre-Sale Support" }],
    featured: false,
},
 {
    slug: "the-skin-diary",
    projectName: "The Skin Diary",
    category: "E-commerce Website Development",
    description: "A cosmetics brand freed from years of patchwork apps and undocumented workarounds, rebuilt on a clean, understandable Shopify foundation.",
    contentFile: "content/case-studies/the-skin-diary.md",
    coverImage: "/portfolio/the-skin-diary.png",
    projectLink: "https://theskindiary.com/",
    metrics: [{ label: "Focus", value: "Tech Stack Audit & Rebuild" }],
    featured: false,
},
  {
    slug: "aurra-perfume",
    projectName: "Aurra Perfume",
    category: "Paid Ads & Conversion Optimization",
    description: "A perfume brand stuck on a plateau despite steady ad spend — fixed by rebuilding both the campaign structure and the store slowing it down.",
    contentFile: "content/case-studies/aurra-perfume.md",
    coverImage: "/portfolio/aurra-perfume.png",
    projectLink: "",
    metrics: [
        { label: "ROAS", value: "5.4x (from 1.8x)" },
        { label: "CAC", value: "$21 (from $48)" },
        { label: "CTR", value: "1.9% (from 0.6%)" },
        { label: "CPC", value: "$1.10 (from $1.85)" },
    ],
    featured: true,
},
{
    slug: "miniclasix",
    projectName: "Miniclasix",
    category: "Paid Ads & Conversion Optimization",
    description: "A baby clothing brand whose ad account looked healthy on the surface — until a funnel split and a sizing fix unlocked the real bottleneck.",
    contentFile: "content/case-studies/miniclasix.md",
    coverImage: "/portfolio/iminiclasix.png",
    projectLink: "",
    metrics: [
        { label: "ROAS", value: "5.7x (from 1.6x)" },
        { label: "CAC", value: "$24 (from $52)" },
        { label: "CTR", value: "2.3% (from 0.9%)" },
        { label: "CPC", value: "$0.95 (from $1.40)" },
    ],
    featured: false,
},
{
    slug: "kayaa-skincare",
    projectName: "Kayaa Skincare",
    category: "Paid Ads & Conversion Optimization",
    description: "A dermatology-backed skincare brand whose real clinical credibility wasn't converting — fixed by rebuilding ad trust signals and surfacing proof on-site.",
    contentFile: "content/case-studies/kayaa-skincare.md",
    coverImage: "/portfolio/kayaa-skincare.png",
    projectLink: "",
    metrics: [
        { label: "ROAS", value: "6.1x (from 1.4x)" },
        { label: "CAC", value: "$26 (from $61)" },
        { label: "CTR", value: "2.1% (from 0.7%)" },
        { label: "CPC", value: "$1.25 (from $2.10)" },
    ],
    featured: false,
},
{
    slug: "the-blue-sky",
    projectName: "The Blue Sky",
    category: "Paid Ads & Conversion Optimization",
    description: "A beachwear brand that nearly paused ad spend over broken tracking data — the ads were working all along, the pixel just wasn't seeing it.",
    contentFile: "content/case-studies/the-blue-sky.md",
    coverImage: "/portfolio/the-blue-sky.png",
    projectLink: "",
    metrics: [
        { label: "ROAS", value: "6.4x (from a reported 1.1x)" },
        { label: "CAC", value: "$19 (from a reported $70)" },
        { label: "CTR", value: "2.0% (from 1.4%)" },
        { label: "CPC", value: "$1.15 (steady)" },
    ],
    featured: false,
},
{
    slug: "luxe-jewellery",
    projectName: "Luxe Jewellery",
    category: "Paid Ads & Conversion Optimization",
    description: "A jewellery brand relying entirely on cold social prospecting — fixed by capturing high-intent search demand and closing trust gaps on-site.",
    contentFile: "content/case-studies/luxe-jewellery.md",
    coverImage: "/portfolio/luxe-jewellery.png",
    projectLink: "",
    metrics: [
        { label: "ROAS", value: "5.8x (from 2.0x)" },
        { label: "CAC", value: "$27 (from $95)" },
        { label: "CTR", value: "1.7% (from 0.8%)" },
        { label: "CPC", value: "$0.90 (from $1.60)" },
    ],
    featured: false,
},
{
    slug: "teesclub",
    projectName: "TeesClub",
    category: "Paid Ads & Conversion Optimization",
    description: "A graphic tee brand whose ads were converting clicks perfectly — until a generic landing page and mismatched sizing quietly killed the sale.",
    contentFile: "content/case-studies/teesclub.md",
    coverImage: "/portfolio/teesclub.png",
    projectLink: "",
    metrics: [
        { label: "ROAS", value: "5.9x (from 1.3x)" },
        { label: "CAC", value: "$14 (from $38)" },
        { label: "CTR", value: "2.3% (steady)" },
        { label: "CPC", value: "$0.90 (steady)" },
    ],
    featured: false,
},
];

export const caseStudies = CASE_STUDIES;
